language: ruby
bundler_args: --without benchmarks
script:
  - bundle exec rake spec
before_install:
  - gem --version
  - |
    bash -c " # Install MariaDB if DB=mariadb
    if [[ x$DB =~ xmariadb ]]; then
      sudo service mysql stop
      sudo apt-get purge '^mysql*' 'libmysql*'
      sudo apt-get install python-software-properties
      sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
      if [[ x$DB = xmariadb55 ]]; then
        sudo add-apt-repository 'deb http://ftp.osuosl.org/pub/mariadb/repo/5.5/ubuntu precise main'
      elif [[ x$DB = xmariadb10 ]]; then
        sudo add-apt-repository 'deb http://ftp.osuosl.org/pub/mariadb/repo/10.0/ubuntu precise main'
      fi
      sudo apt-get update
      sudo apt-get -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold -y install mariadb-server libmariadbd-dev
    fi
    "
  - |
    bash -c " # Install MySQL is OS=darwin
    if [[ x$OSTYPE =~ ^xdarwin ]]; then
      brew install mysql
      mysql.server start
    fi
    "
  - mysqld --version
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS test"
os:
  - linux
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - ree
matrix:
  allow_failures:
    - rvm: rbx-2
  include:
    - rvm: 2.0.0
      env: DB=mariadb55
    - rvm: 2.0.0
      env: DB=mariadb10
    - rvm: rbx-2
      env: RBXOPT=-Xgc.honor_start=true
    - rvm: 2.0.0
      os: osx
